using Content.Client._EstacaoPirata.Cards.Hand.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.Pleebnar;
using Content.Shared.Speech;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Impstation.Pleebnar;

[GenerateTypedNameReferences]
public sealed partial class PleebnarTelepathyWindow : FancyWindow
{
    public Action<string?>? OnVisionSelect;
    public Action? OnConfirm;
    private string? _vision;
    private List<(string, string)> _visions = new();
    private RadioOptions<string> _visionsbuttons;
    private int prevsize = 0;
    public PleebnarTelepathyWindow()
    {
        RobustXamlLoader.Load(this);
        _visionsbuttons = new RadioOptions<string>(RadioOptionsLayout.Vertical);
        visionsVbox.AddChild(_visionsbuttons);
        _visionsbuttons.OnItemSelected += args =>
        {
            OnVisionSelect?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
        };
    }
    public void ReloadVisions(IPrototypeManager proto)
    {
        foreach (var vision in proto.EnumeratePrototypes<PleebnarVisionPrototype>())
        {
            _visions.Add((Loc.GetString(vision.Name), vision.ID));
        }
        _visions.Sort((a, b) => a.Item1.CompareTo(b.Item1));
    }

    public void AddVisions()
    {
        _visionsbuttons.Clear();
        foreach (var (name, id) in _visions)
        {
            AddVision(name, id);
        }
    }

    private void AddVision(string name, string vision)
    {
        var id = _visionsbuttons.ItemCount;
        _visionsbuttons.AddItem(Loc.GetString(name), vision);
        if (vision is { } metadata)
        {
            _visionsbuttons.SetItemMetadata(id, metadata);
        }

        if (vision == _vision)
            _visionsbuttons.Select(id);
    }

    public void UpdateState(string? vision)
    {
        _vision = vision;

        for (int id = 0; id < _visionsbuttons.ItemCount; id++)
        {
            if (string.Equals(vision, _visionsbuttons.GetItemMetadata(id)))
            {
                _visionsbuttons.Select(id);
                break;
            }
        }
    }
}
