// SPDX-FileCopyrightText: 2025 Evaisa <evagiacosa1@gmail.com>
// SPDX-FileCopyrightText: 2025 EvaisaDev <mail@evaisa.dev>
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using Content.Shared.Access.Components;
using Content.Shared.CCVar; // imp
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // imp

namespace Content.Client._Funkystation.NanoChat;

[GenerateTypedNameReferences]
public sealed partial class CreateGroupChatPopup : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!; // imp

    public event Action<string>? OnGroupCreated;

    private int _maxNameLength; // imp

    public CreateGroupChatPopup()
    {
        IoCManager.InjectDependencies(this); // imp
        RobustXamlLoader.Load(this);

        _maxNameLength = _cfg.GetCVar(CCVars.MaxNameLength); // imp

        ContentsContainer.Margin = new Thickness(3);

        // Button handlers
        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => CreateGroup();

        // Input validation
        GroupNameInput.OnTextEntered += _ => CreateGroup();

        GroupNameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > _maxNameLength) // imp max name length change
                GroupNameInput.Text = args.Text[.._maxNameLength]; // imp, ditto
            ValidateInputs();
        };
    }

    private void ValidateInputs()
    {
        var isValid = !string.IsNullOrWhiteSpace(GroupNameInput.Text);
        CreateButton.Disabled = !isValid;
    }

    private void CreateGroup()
    {
        if (CreateButton.Disabled)
            return;

        var name = GroupNameInput.Text.Trim();
        OnGroupCreated?.Invoke(name);
        Close();
    }

    public void ClearInputs()
    {
        GroupNameInput.Text = string.Empty;
        ValidateInputs();
    }
}
