using Content.Shared.Antag;
using Robust.Shared.GameStates;
using Content.Shared.StatusIcon;
using Robust.Shared.Prototypes;
using Robust.Shared.Audio;
using Content.Shared.Item;
using Content.Shared.Damage;
using System.Threading;
using Content.Shared._Impstation.CosmicCult.Prototypes;

namespace Content.Shared._Impstation.CosmicCult.Components;

/// <summary>
/// Added to mind role entities to tag that they are a cosmic cultist.
/// </summary>
[RegisterComponent, NetworkedComponent]
[AutoGenerateComponentState]
public sealed partial class CosmicCultComponent : Component
{
    #region Housekeeping

    /// <summary>
    /// The status icon prototype displayed for cosmic cultists.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public ProtoId<FactionIconPrototype> StatusIcon { get; set; } = "CosmicCultIcon";

    [DataField]
    public bool IsConstruct = false;

    #endregion

    #region Ability Data
    [DataField] public List<ProtoId<InfluencePrototype>> UnlockedInfluences = new()
    {
        "InfluenceAberrantLapse",
        "InfluenceNullGlare",
        "InfluenceEschewMetabolism",
    };

    public List<ProtoId<EntityPrototype>> CosmicCultActions = new()
    {
        "ActionCosmicSiphon",
        "ActionCosmicBlank",
    };
    public List<EntityUid?> ActionEntities = new();

    /// <summary>
    /// The duration of the doAfter for cosmic siphon
    /// </summary>
    [DataField, AutoNetworkedField] public TimeSpan CosmicSiphonSpeed = TimeSpan.FromSeconds(4);

    /// <summary>
    /// The duration of the doAfter for cosmic blank
    /// </summary>
    [DataField, AutoNetworkedField] public TimeSpan CosmicBlankSpeed = TimeSpan.FromSeconds(0.6f);

    /// <summary>
    /// The duration of cosmic blank's trip to the void
    /// </summary>
    [DataField, AutoNetworkedField] public TimeSpan CosmicBlankDuration = TimeSpan.FromSeconds(22);

    /// <summary>
    /// The amount of Entropy generated by Cosmic siphon.
    /// </summary>
    [DataField] public int CosmicSiphonQuantity = 1;
    /// <summary>
    /// The amount of Entropy the user is allowed to spend at The Monument.
    /// </summary>
    [DataField] public int EntropyBudget = 0;

    /// <summary>
    /// Wether or not this cultist has been empowered by a Malign Rift.
    /// </summary>
    [DataField] public bool CosmicEmpowered = false;

    /// <summary>
    /// The damage to apply upon a successful cosmic siphon
    /// </summary>
    [DataField, AutoNetworkedField]
    public DamageSpecifier CosmicSiphonDamage = new()
    {
        DamageDict = new() {
            { "Asphyxiation", 25 }
        }
    };
    #endregion

    #region VFX & SFX

    [DataField] public EntProtoId SpawnWisp = "MobCosmicWisp";

    [DataField] public EntProtoId LapseVFX = "CosmicLapseAbilityVFX";

    [DataField] public EntProtoId BlankVFX = "CosmicBlankAbilityVFX";

    [DataField] public EntProtoId AbsorbVFX = "CosmicGlyphVFX";

    [DataField] public SoundSpecifier BlankSFX = new SoundPathSpecifier("/Audio/_Impstation/CosmicCult/ability_blank.ogg");

    #endregion
}
