using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Content.Shared.Hands.Components;
using Content.Shared.Hands.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class POSMenu : FancyWindow
{
    [Dependency] private readonly IPlayerManager _playerMan = null!;
    [Dependency] private readonly IEntityManager _entityManager = null!;

    public Action<string>? OnNumberEntered;
    public Action? OnClearButtonPressed;

    private bool _accountOpen;

    public POSMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CreateInvalidSetupBox();

        UIKeypad.OnClearButtonPressed += () => OnClearButtonPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        CheckForCard();
    }

    private void CheckForCard()
    {
        //if we've already got an open account, we are the server or the player entity does not have hands, return
        if (_accountOpen || _playerMan.LocalEntity is not { } realEnt || !_entityManager.HasComponent<HandsComponent>(realEnt))
        {
            return;
        }

        //go over everything that's held by the player
        var handSystem = _entityManager.System<SharedHandsSystem>();
        var held = handSystem.EnumerateHeld(realEnt);
        foreach (var ent in held)
        {
            //if it's not a bank card, continue
            if (!_entityManager.TryGetComponent<BankCardComponent>(ent, out var comp))
                continue;

            //set the entered number & invoke the number entered action
            UIKeypad.SetEnteredNumber($"{comp.AccessNumber.Number:000000}");
            OnNumberEntered?.Invoke($"{comp.AccessNumber.Number:000000}");
            break;
        }
    }

    public void ClearBox()
    {
        MainContainer.RemoveAllChildren();
        _accountOpen = false;
    }

    public PoSSetupBox CreateSetupBox()
    {
        ClearBox();
        var box = new PoSSetupBox(true);
        MainContainer.AddChild(box);
        _accountOpen = true;
        return box;
    }

    public PoSSetupBox CreateInvalidSetupBox()
    {
        ClearBox();
        var box = new PoSSetupBox(false);
        MainContainer.AddChild(box);
        return box;
    }

    public PoSPaymentBox CreatePaymentBox()
    {
        ClearBox();
        var box = new PoSPaymentBox(true);
        MainContainer.AddChild(box);
        _accountOpen = true;
        return box;
    }

    public PoSPaymentBox CreateInvalidPaymentBox()
    {
        ClearBox();
        var box = new PoSPaymentBox(false);
        MainContainer.AddChild(box);
        return box;
    }
}

