using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class PoSPaymentBox : Control
{

    public Action? TransactionConfirmed;
    public Action? TransactionCancelled;

    public PoSPaymentBox()
    {
        RobustXamlLoader.Load(this);
    }

    public PoSPaymentBox(bool valid)
    {
        RobustXamlLoader.Load(this);
        MainContainer.Visible = valid;
        NamingThingsIsHard.Visible = !valid;

        ConfirmTransactionButton.OnPressed += _ => TransactionConfirmed?.Invoke();
        CancelButton.OnPressed += _ => TransactionCancelled?.Invoke();
    }

    public void FillOutDetails(string name, TransferNumber number, int amount, string reason)
    {
        NameAndNumberLabel.Text =
            Loc.GetString("pos-payment-name-and-number", ("name", name), ("number", $"{number.Number:0000}"));
        ChargeAmountLabel.Text = Loc.GetString("pos-payment-spesito-amount", ("amount", $"{amount:n0}"));
        ChargeReasonLabel.Text =
            string.IsNullOrEmpty(reason) ? "" : Loc.GetString("pos-payment-reason", ("reason", reason));
    }
}

