using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class PoSSetupBox : Control
{
    public Action? OnSetupConfirmed;
    public Action? OnSetupCleared;

    public int TransferAmount = 0;

    public PoSSetupBox()
    {
        RobustXamlLoader.Load(this);
    }

    public PoSSetupBox(bool valid)
    {
        RobustXamlLoader.Load(this);

        ValidityLabel.Text =
            valid ? Loc.GetString("pos-begin-setup-text") : Loc.GetString("pos-begin-setup-present-card");
        BeginSetupButton.Disabled = !valid;

        BeginSetupButton.OnPressed += _ =>
        {
            StartDialogueBox();
        };

        SetupClearButton.OnPressed += _ => OnSetupCleared?.Invoke();
        SetupConfirmButton.OnPressed += _ => OnSetupConfirmed?.Invoke();

        //todo should probably pr a NumberEdit thing to wizden to make this less evil
        TransferNoEntryBox.OnTextChanged += args =>
        {
            var numberStr = string.Concat(args.Text.Where(char.IsDigit));
            if (numberStr.Length > 4)
                numberStr = numberStr[..4];

            TransferNoEntryBox.Text = numberStr;
        };

        //todo need to make it so that this can be fully cleared
        TransferAmountEntryBox.OnTextChanged += args =>
        {
            var amountStr = string.Concat(args.Text.Where(char.IsDigit));
            if (amountStr.Length > 9)
                amountStr = amountStr[..9];

            if (int.TryParse(amountStr, out var amount))
            {
                TransferAmount = amount;
            }

            TransferAmountEntryBox.Text = $"{TransferAmount:n0}";
        };

        CharsRemainingLabel.Text = Loc.GetString("atm-transfer-reason-charcount", ("count", 64));

        TransferReasonEntryBox.OnTextChanged += args =>
        {
            var len = args.Text.Length;
            if (len > 64)
            {
                TransferReasonEntryBox.Text = args.Text[..64];
            }

            CharsRemainingLabel.Text = Loc.GetString("atm-transfer-reason-charcount", ("count", 64 - len));
        };
    }

    public void FillOutDetails(int accountNo, int amount, string reason)
    {
        StartDialogueBox();

        if (accountNo != 0)
            TransferNoEntryBox.SetText($"{accountNo:0000}");
        if (amount != 0)
            TransferAmountEntryBox.SetText($"{amount}");
        if (!string.IsNullOrEmpty(reason))
            TransferReasonEntryBox.SetText(reason);
    }

    private void StartDialogueBox()
    {
        NamingThingsIsHard.Visible = false;
        SetupDialogueBox.Visible = true;
    }
}

