using Content.Shared._Impstation.StrangeMoods;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Impstation.StrangeMoods.Eui;

[GenerateTypedNameReferences]
public sealed partial class MoodContainer : BoxContainer
{
    public event Action? OnMoveUp;
    public event Action? OnMoveDown;
    public event Action? OnDelete;

    public MoodContainer(StrangeMood? mood = null)
    {
        RobustXamlLoader.Load(this);

        if (mood != null)
        {
            StrangeMoodTitle.Text = mood.GetLocName();
            StrangeMoodContent.TextRope = new Rope.Leaf(mood.GetLocDesc());
        }

        MoveUp.OnPressed += _ => OnMoveUp?.Invoke();
        MoveDown.OnPressed += _ => OnMoveDown?.Invoke();
        Delete.OnPressed += _ => OnDelete?.Invoke();
    }

    public string MoodTitle => StrangeMoodTitle.Text;
    public string MoodText => Rope.Collapse(StrangeMoodContent.TextRope).Trim();
}
