using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.StrangeMoods;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.StrangeMoods;

[GenerateTypedNameReferences]
public sealed partial class StrangeMoodsMenu : FancyWindow
{
    public StrangeMoodsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(StrangeMoodsComponent comp, StrangeMoodsBuiState state)
    {
        MoodDisplayContainer.Children.Clear();

        foreach (var mood in state.SharedMoods)
            MoodDisplayContainer.AddChild(new MoodDisplay(mood, true));

        foreach (var mood in comp.Moods)
            MoodDisplayContainer.AddChild(new MoodDisplay(mood, false));
    }
}
