- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Elkridge
  #- Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  #- Exo
  # IMP MAPS BELOW:
  - Banana
  - Barratry
  - Bedlam
  - Boat
  - Cog
  - Convex
  - Core
  - Gate
  - Hash
  - Hummingbird
  - Lilboat
  - Luna
  - Omega
  - Saltern
  - Submarine
  - Train
  - Xeno
