- type: antag
  id: BloodlessChimp
  name: roles-antag-bloodless-chimp-name
  antagonist: true
  playTimeTracker: AntagBloodlessChimp
  objective: roles-antag-bloodless-chimp-objective
  SetPreference: false
