- type: antag
  id: SlasherRole
  name: roles-antag-slasher-name
  antagonist: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h
  playTimeTracker: AntagSlasher
  setPreference: true
  objective: roles-antag-slasher-description
  guides: [ Slashers ]

- type: startingGear
  id: BountyHunterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    head: ClothingHeadHatCowboyBountyHunter
    mask: ClothingMaskGasSecurity
    back: ClothingBackpackSatchel
    eyes: ClothingEyesBountyHunterGlasses
    outerClothing: ClothingOuterCoatBomber
    shoes: ClothingShoesBootsMercFilled
    gloves: ClothingHandsMercGlovesCombat
    id: BountyHunterPDA
    ears: ClothingHeadsetFreelance
    belt: ClothingBeltMercWebbing
    pocket1: BaseSeclinkRadio
    pocket2: BountyHunterGear
  storage:
    back:
    - WeaponRevolverInspector
    - SmokeGrenade
