using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class AccountInfoBox : BoxContainer
{

    public Action? OnTransactionButtonPressed;

    public AccountInfoBox()
    {
        RobustXamlLoader.Load(this);
    }

    public AccountInfoBox(Entity<BankAccountComponent> account)
    {
        RobustXamlLoader.Load(this);

        TransferFundsButton.OnPressed += _ => OnTransactionButtonPressed?.Invoke();

        AccNameLabel.Text = Loc.GetString("atm-machine-account-name-title", ("name", account.Comp.Name));
        AccAccessNumberLabel.Text = Loc.GetString("atm-machine-account-access-number-title", ("number", $"{account.Comp.AccessNumber:000000}"));
        AccTransferNumberLabel.Text = Loc.GetString("atm-machine-account-transfer-number-title", ("number", $"{account.Comp.TransferNumber:0000}"));
        AccBalanceLabel.Text = Loc.GetString("atm-machine-account-balance-title", ("balance", $"{account.Comp.Balance:n0}"));

        if (account.Comp.Transactions.Count == 0)
        {
            NoTransactionsLabel.Visible = true;
            TransactionInfoBoxScroller.Visible = false;
        }
        else
        {
            NoTransactionsLabel.Visible = false;
            TransactionInfoBoxScroller.Visible = true;

            FillOutTransactionInfo();
        }
    }

    //todo write this
    private void FillOutTransactionInfo()
    {

    }
}

