using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class AccountInfoBox : BoxContainer
{

    public Action? OnTransactionButtonPressed;

    public AccountInfoBox()
    {
        RobustXamlLoader.Load(this);
    }

    public AccountInfoBox(BankAccount account)
    {
        RobustXamlLoader.Load(this);

        TransferFundsButton.OnPressed += _ => OnTransactionButtonPressed?.Invoke();

        AccNameLabel.Text = Loc.GetString("atm-machine-account-name-title", ("name", account.Name));
        AccAccessNumberLabel.Text = Loc.GetString("atm-machine-account-access-number-title", ("number", $"{account.AccessNumber:000000}"));
        AccTransferNumberLabel.Text = Loc.GetString("atm-machine-account-transfer-number-title", ("number", $"{account.TransferNumber:0000}"));
        AccBalanceLabel.Text = Loc.GetString("atm-machine-account-balance-title", ("balance", $"{account.Balance:n0}"));

        if (account.Transactions.Count == 0)
        {
            var noTransactionsLabel = new Label();
            noTransactionsLabel.Text = Loc.GetString("atm-machine-no-transactions");
            noTransactionsLabel.VerticalExpand = true;
            noTransactionsLabel.HorizontalExpand = true;
            noTransactionsLabel.HorizontalAlignment = HAlignment.Center;
            noTransactionsLabel.VerticalAlignment = VAlignment.Center;
            noTransactionsLabel.Align = Label.AlignMode.Center;
            TransactionInfoContainer.AddChild(noTransactionsLabel);
        }
        else
        {
            //actually fill out transaction data here
        }
    }
}

