using System.Linq;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class AccountInfoBox : BoxContainer
{

    public Action? OnTransactionButtonPressed;

    private Entity<BankAccountComponent> _account;

    public AccountInfoBox()
    {
        RobustXamlLoader.Load(this);
    }

    public AccountInfoBox(Entity<BankAccountComponent> account)
    {
        RobustXamlLoader.Load(this);

        //todo make this update as transactions happen etc etc
        //just frameUpdate this shit?
        _account = account;

        TransferFundsButton.OnPressed += _ => OnTransactionButtonPressed?.Invoke();

        AccNameLabel.Text = Loc.GetString("atm-machine-account-name-title", ("name", account.Comp.Name));
        AccAccessNumberLabel.Text = Loc.GetString("atm-machine-account-access-number-title", ("number", $"{account.Comp.AccessNumber.Number:000000}"));
        AccTransferNumberLabel.Text = Loc.GetString("atm-machine-account-transfer-number-title", ("number", $"{account.Comp.TransferNumber.Number:0000}"));

    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        AccBalanceLabel.Text = Loc.GetString("atm-machine-account-balance-title", ("balance", $"{_account.Comp.Balance:n0}"));

        if (_account.Comp.Transactions.Count == 0 || !NeedsInfoboxRebuild())
            return;

        TransactionInfoContainer.RemoveAllChildren();
        foreach (var transaction in _account.Comp.Transactions)
        {
            var infobox = new TransactionInfoBox(transaction.OtherAccount, transaction.Name, transaction.Amount, transaction.Timestamp, transaction.Reason);
            TransactionInfoContainer.AddChild(infobox);
        }
    }

    private bool NeedsInfoboxRebuild()
    {
        //for every transaction in the list
        foreach (var transaction in _account.Comp.Transactions)
        {
            var infoboxExists = false;
            //if they don't have a corresponding info box, return true
            //notionally this only needs to check the first transactioninfo container since transactions always get added to the front of the list, but let's be safe
            foreach (var child in TransactionInfoContainer.Children)
            {
                //child isn't an infobox, ignore it
                if (child is not TransactionInfoBox { } infoBox)
                    continue;

                //they are equal, the infobox exists
                if (CompTransactionToInfobox(transaction, infoBox))
                    infoboxExists = true;
            }

            //if it doesn't exist, break out of the loop and rebuild the list
            if (!infoboxExists)
                return true;
        }

        return false;
    }

    private bool CompTransactionToInfobox(BankTransaction transaction, TransactionInfoBox infoBox)
    {
        return transaction.OtherAccount == infoBox.Other &&
               transaction.Amount == infoBox.Amount &&
               // ReSharper disable once CompareOfFloatsByEqualityOperator - we only care if the timestamps are literally identical
               transaction.Timestamp == infoBox.Timestamp &&
               transaction.Reason == infoBox.Reason;
    }
}

