using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Content.Shared.Hands.Components;
using Content.Shared.Hands.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class ATMMenu : FancyWindow
{
    [Dependency] private readonly IPlayerManager _playerMan = null!;
    [Dependency] private readonly IEntityManager _entityManager = null!;

    public Action<string>? OnNumberEntered;
    public Action? OnClearButtonPressed;

    private bool _accountOpen;

    public ATMMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UIKeypad.OnEnterButtonPressed += s => OnNumberEntered?.Invoke(s);
        UIKeypad.OnClearButtonPressed += () => OnClearButtonPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        //if we've already got an open account, we are the server or the player entity does not have hands, return
        if (_accountOpen || _playerMan.LocalEntity is not { } realEnt || !_entityManager.HasComponent<HandsComponent>(realEnt))
        {
            return;
        }

        //go over everything that's held by the player
        var handSystem = _entityManager.System<SharedHandsSystem>();
        var held = handSystem.EnumerateHeld(realEnt);
        foreach (var ent in held)
        {
            //if it's not a bank card, continue
            if (!_entityManager.TryGetComponent<BankCardComponent>(ent, out var comp))
                continue;

            //set the entered number & invoke the number entered action
            UIKeypad.SetEnteredNumber($"{comp.AccessNumber:000000}");
            OnNumberEntered?.Invoke($"{comp.AccessNumber:000000}");
            break;
        }
    }

    public void CreateInvalidInfoBox()
    {
        ClearInfoBox();

        var infoBox = new NoAccountInfoBox();
        AccountInfoContainer.AddChild(infoBox);
    }

    public void CreateInfoBoxForAccount(BankAccount account)
    {
        ClearInfoBox();

        var infobox = new AccountInfoBox(account);
        AccountInfoContainer.AddChild(infobox);
        _accountOpen = true;
    }

    public void ClearInfoBox()
    {
        AccountInfoContainer.RemoveAllChildren();
        _accountOpen = false;
    }
}
