using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class Keypad : Control
{
    public int NumberLength { get; set; } = 6;

    private string _enteredNumber = ""; //todo this can probably be an int can't it

    public Action<string>? OnEnterButtonPressed;
    public Action? OnClearButtonPressed;

    public Keypad()
    {
        RobustXamlLoader.Load(this);

        SetupGrid();
    }

    public void SetEnteredNumber(string number)
    {
        _enteredNumber = number;
        NumberDisplay.Text = _enteredNumber;
    }

    private void NumberButtonPressed(int i)
    {
        if (_enteredNumber.Length >= NumberLength)
            return; //clear the number manually if we're at the limit

        _enteredNumber += i;
        NumberDisplay.Text = _enteredNumber;
    }

    private void ClearButtonPressed()
    {
        _enteredNumber = "";
        NumberDisplay.Text = _enteredNumber;
        OnClearButtonPressed?.Invoke();
    }

    private void EnterButtonPressed()
    {
        OnEnterButtonPressed?.Invoke(_enteredNumber);
    }

    private void SetupGrid()
    {
        OneButton.OnPressed += _ => NumberButtonPressed(1);
        TwoButton.OnPressed += _ => NumberButtonPressed(2);
        ThreeButton.OnPressed += _ => NumberButtonPressed(3);
        FourButton.OnPressed += _ => NumberButtonPressed(4);
        FiveButton.OnPressed += _ => NumberButtonPressed(5);
        SixButton.OnPressed += _ => NumberButtonPressed(6);
        SevenButton.OnPressed += _ => NumberButtonPressed(7);
        EightButton.OnPressed += _ => NumberButtonPressed(8);
        NineButton.OnPressed += _ => NumberButtonPressed(9);
        ZeroButton.OnPressed += _ => NumberButtonPressed(0);

        ClearButton.OnPressed += _ => ClearButtonPressed();
        EnterButton.OnPressed += _ => EnterButtonPressed();
    }
}

