using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class NoAccountInfoBox : BoxContainer
{
    public NoAccountInfoBox()
    {
        RobustXamlLoader.Load(this);
    }
}

