using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class TransactionMenu : FancyWindow
{

    public Action? TransactionConfirmAttempt;
    public Action? TransactionConfirmed;

    public int TransferAmount;

    public TransactionMenu()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => TransactionConfirmAttempt?.Invoke();

        ReallyConfirmButton.OnPressed += _ => TransactionConfirmed?.Invoke();

        CancelButton.OnPressed += _ => Close();

        TransferNumberBox.OnTextChanged += args =>
        {
            var numberStr = string.Concat(args.Text.Where(char.IsDigit));
            if (numberStr.Length > 4)
                numberStr = numberStr[..4];

            TransferNumberBox.Text = numberStr;
        };

        //todo this acts strangely sometimes, need to figure out why
        TransferAmountBox.OnTextChanged += args =>
        {
            var amountStr = string.Concat(args.Text.Where(char.IsDigit));
            if (amountStr.Length > 9)
                amountStr = amountStr[..9];

            if (int.TryParse(amountStr, out var amount))
            {
                TransferAmount = amount;
            }

            TransferAmountBox.Text = $"{TransferAmount:n0}";
        };

        CharsRemainingLabel.Text = Loc.GetString("atm-transfer-reason-charcount", ("count", 64));

        TransferReasonBox.OnTextChanged += args =>
        {
            var len = args.Text.Length;
            if (len > 64)
            {
                TransferReasonBox.Text = args.Text[..64];
            }

            CharsRemainingLabel.Text = Loc.GetString("atm-transfer-reason-charcount", ("count", 64 - len));
        };
    }
}
