using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class TransactionInfoBox : Control
{
    public readonly TransferNumber Other;
    public readonly int Amount;
    public readonly string Reason = "";

    public TransactionInfoBox()
    {
        RobustXamlLoader.Load(this);
    }

    public TransactionInfoBox(TransferNumber other, int amount, string reason)
    {

        RobustXamlLoader.Load(this);

        Other = other;
        Amount = amount;
        Reason = reason;
        
        TransferNoLabel.Text = $"#{other.Number:0000}";
        AmountLabel.Text = $"{amount:n0}";

        //todo proper custom tooltipsupplier for this
        ToolTip = amount < 0
            ? $"You sent account #{other.Number:0000} ${int.Abs(amount)} spesitos for \"{reason}\""
            : $"You recieved ${amount} spesitos from account #{other} for \"{reason}\"";
    }
}

