- type: startingGear
  id: NewWizardGear # to do special gear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    back: ClothingBackpack
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    ears: ClothingHeadsetAltWizard
    belt: ClothingBeltWandFilled
