using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.AccountManagement;

[GenerateTypedNameReferences]
public sealed partial class AccountInfoSelectorButtonThing : Control
{
    public AccountInfoSelectorButtonThing()
    {
        RobustXamlLoader.Load(this);
    }

    public AccountInfoSelectorButtonThing(Entity<BankAccountComponent> account)
    {
        RobustXamlLoader.Load(this); //todo make this work gooder. need to make it a custom control type that handles clicks etc etc itself

        TransferNumberLabel.Text = $"{((int) account.Comp.TransferNumber):0000}";
    }
}

