using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.AccountManagement;

[GenerateTypedNameReferences]
public sealed partial class AccountManagementMenu : FancyWindow
{
    public AccountManagementMenu()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(SalaryPanel, Loc.GetString("salary-panel-tab-name"));
        TabContainer.SetTabTitle(DetailPanel, Loc.GetString("detail-panel-tab-name"));
    }

    public void FillOutAccountButtons(IEntityManager entMan)
    {
        var accountQuery = entMan.EntityQueryEnumerator<BankAccountComponent>();
        while (accountQuery.MoveNext(out var uid, out var comp))
        {
            var selector = new AccountInfoSelectorButtonThing((uid, comp));
            SalaryPanel.AddSelectorThingToList(selector);
        }
    }
}

