using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.AccountManagement;

[GenerateTypedNameReferences]
public sealed partial class SalaryManagementPanel : BoxContainer
{
    public SalaryManagementPanel()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddSelectorThingToList(AccountInfoSelectorButtonThing thing)
    {
        AccountInfoSelectorContainer.AddChild(thing);
        AccountInfoSelectorContainer.InvalidateArrange();
        AccountInfoSelectorContainer.InvalidateMeasure();
    }
}

