- type: entity # for goblins
  parent: BaseMindRole
  id: MindRoleGhostRoleTeamFreeAgent
  name: Ghost Role (Team Free Agent)
  components:
  - type: MindRole
    roleType: FreeAgent
  - type: GhostRoleMarkerRole

#Lone Op
- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsLone
  name: Lone Operative Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    antagPrototype: NukeopsLone
  - type: NukeopsRole
