- type: gameMapPool
  id: DefaultMapPoolImp
  maps:
  # WIZDEN MAPS
  - AmberImp
  - BagelImp
  - BoxImp
  - Cluster
  - CogImp
  - CoreImp
  - ElkridgeImp
  - GateImp
  - MarathonImp
  - OasisImp
  - PackedImp
  - PlasmaImp
  - ReachImp
  - SalternImp
  #- SnowballImp, playtests required
  - TrainImp
  - Xeno #aka exo
  # IMP MAPS:
  - Banana
  - Bedlam
  - Boat
  - Hummingbird
  - Lilboat
  #- Monarch
  #- Luna
  - Pathway
  - Union
  - Whisper
  # DELTAV MAPS:
  - Submarine
  # HARMONY MAPS:
  - Barratry
  #- Eclipse
